# ~/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
#[ -z "$PS1" ] && return

# don't put duplicate lines in the history. See bash(1) for more options
export HISTCONTROL=ignoredups

export EDITOR=vim

# Format cucumber nicely
export CUCUMBER_FORMAT=pretty

# make autotest run cukes if they're there
export AUTOFEATURE=true

# Titanium Developer
export TIPATH=~/.titanium

export ANDROID_HOME=~/software/android/android-studio/sdk

export PATH=$PATH:~/bin
export PATH=$PATH:$ANDROID_HOME/platform-tools
export PATH=$PATH:~/software/gradle-1.12/bin

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(lesspipe)"

# screw less/more, just use most
[ -x /usr/bin/most ] && export PAGER=most
[ -x /usr/bin/most ] && alias more='most' && alias less='most'

# set variable identifying the chroot you work in (used in the prompt below)
if [ -z "$debian_chroot" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
xterm-color)
    PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
    ;;
*)
    PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\$ '
    ;;
esac

# If this is an xterm set the title to user@host:dir
case "$TERM" in
xterm*|rxvt*)
    PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME}: ${PWD/$HOME/~}\007"'
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases
if [ "$TERM" != "dumb" ]; then
    eval "`dircolors -b`"
    alias ls='ls --color=auto'
    alias dir='ls --color=auto --format=vertical'
    alias vdir='ls --color=auto --format=long'
fi

# some more ls aliases
alias ll='ls -l'
alias la='ls -A'
alias l='ls -CF'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
fi

# Person (non-public) bashrc bits should live in this file.
if [ -f ~/.bash_files/personal ]; then
  . ~/.bash_files/personal
fi

if [ -f ~/.bash_files/aliases ]; then
  . ~/.bash_files/aliases
fi

source ~/liquidprompt/liquidprompt
#if [ -f ~/.bash_files/prompts/elite ]; then
  #. ~/.bash_files/prompts/elite
  #elite
#fi
#export PS1='C:${PWD//\//\\\}>'

[[ -s $HOME/.rvm/scripts/rvm ]] && source $HOME/.rvm/scripts/rvm
[[ -s ./.rvmrc ]] && source ./.rvmrc

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

#xmodmap ~/.xmodmap-esc

source /home/jadams/erlang/erlangs/17.4/activate

### Added by the Heroku Toolbelt
export PATH="/usr/local/heroku/bin:$PATH"
[[ -s "$HOME/.kiex/scripts/kiex" ]] && source "$HOME/.kiex/scripts/kiex"

eval "$(direnv hook bash)"

# For the arch laptop
export LIBGL_DRIVERS_PATH=/usr/lib32/xorg/modules/dri
